// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKxjdguY5Kc1Cf6g1e7xYimFpDUdyXys',
    appId: '1:6690397156:web:22bcb9633629bb7d0bc5f1',
    messagingSenderId: '6690397156',
    projectId: 'neo-0-4c500',
    authDomain: 'neo-0-4c500.firebaseapp.com',
    storageBucket: 'neo-0-4c500.appspot.com',
    measurementId: 'G-XXRN5VB6C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbVkKnktq1wiXCIs61ol0kme-xZcF1To',
    appId: '1:6690397156:android:197a88c9aa1182f80bc5f1',
    messagingSenderId: '6690397156',
    projectId: 'neo-0-4c500',
    storageBucket: 'neo-0-4c500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYriRT6-qCGB6KAUGo7U-nLli2Gtau-U',
    appId: '1:6690397156:ios:53a8c9ff4488c1130bc5f1',
    messagingSenderId: '6690397156',
    projectId: 'neo-0-4c500',
    storageBucket: 'neo-0-4c500.appspot.com',
    iosClientId: '6690397156-fllts4iagnla715rsgr3u971nj8aoedq.apps.googleusercontent.com',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYriRT6-qCGB6KAUGo7U-nLli2Gtau-U',
    appId: '1:6690397156:ios:53a8c9ff4488c1130bc5f1',
    messagingSenderId: '6690397156',
    projectId: 'neo-0-4c500',
    storageBucket: 'neo-0-4c500.appspot.com',
    iosClientId: '6690397156-fllts4iagnla715rsgr3u971nj8aoedq.apps.googleusercontent.com',
    iosBundleId: 'com.example.neo',
  );
}
